/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vktxoksvfnkjodjibsxy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrdHhva3N2Zm5ram9kamlic3h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2MTk3NzgsImV4cCI6MjA4NzE5NTc3OH0.lZD7-lOKe5SNW8s6J02LIe-xxfUOYJKy6Aup-sVMkYg"